name: PeyangPaperUtils
version: '${project.version}'
main: net.kunmc.lab.peyangpaperutils.PeyangPaperUtils
api-version: 1.16
authors: [Peyang]
description: A utils for Paper server that made by Peyang.
website: https://kunmc.net/
